### ISSUE TITLE
Practica de GPS con Realidad Aumentada

### ISSUE THREAD

**Issue by ArteezyOne** [SistemasTecTlaxiaco/practica-de-gps-joel#2]
[Practica de GPS con Realidad Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-gps-joel/files/6450163/Practica.de.GPS.con.Realidad.Aumentada.pdf)

**Comment by ObedG** [comment]
Calificación :20

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
